### ISSUE TITLE
la libreria non è fissata al muro

### ISSUE THREAD

**Issue by garak** [magobaol/yl-lib#1]
Si vedono le linguette che penzolano!

**Comment by giorrrgio** [comment]
:+1:

**Comment by magobaol** [comment]
I sistemi di fissaggio delle librerie sono sul retro, non sul fronte. Questa libreria non fa eccezione e infatti era già fissata tramite due staffette sul retro.
Quelle che vedi penzolare sono in realtà due fettucce attaccate al lampadario, per prolungare le due cordicelle che consentono di accendere la luce o il ventilatore.
